DROP TABLE IF EXISTS `im_game`.`tbl_account`;

CREATE TABLE `im_game`.`tbl_account` (
  `account_no` BIGINT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `withdraw_date` DATETIME DEFAULT NULL,
  `withdraw` BOOLEAN DEFAULT FALSE,
  `block_date` DATETIME DEFAULT NULL,
  `block` BOOLEAN DEFAULT FALSE,
  `last_access_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`account_no`),
  UNIQUE KEY `index_unique_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;